from . import KEYWORD


class NON_RESERVED(KEYWORD):
    def __init__(self, name) -> None:
        super().__init__(name, reserved=False)


ABSOLUTE = NON_RESERVED("ABSOLUTE")

ACTION = NON_RESERVED("ACTION")

ADA = NON_RESERVED("ADA")

ADD = NON_RESERVED("ADD")

ADMIN = NON_RESERVED("ADMIN")

AFTER = NON_RESERVED("AFTER")

ALWAYS = NON_RESERVED("ALWAYS")

ASC = NON_RESERVED("ASC")

ASSERTION = NON_RESERVED("ASSERTION")

ASSIGNMENT = NON_RESERVED("ASSIGNMENT")

ATTRIBUTE = NON_RESERVED("ATTRIBUTE")

ATTRIBUTES = NON_RESERVED("ATTRIBUTES")

BEFORE = NON_RESERVED("BEFORE")

BERNOULLI = NON_RESERVED("BERNOULLI")

BREADTH = NON_RESERVED("BREADTH")

CASCADE = NON_RESERVED("CASCADE")

CATALOG = NON_RESERVED("CATALOG")

CATALOG_NAME = NON_RESERVED("CATALOG_NAME")

CHAIN = NON_RESERVED("CHAIN")

CHARACTER_SET_CATALOG = NON_RESERVED("CHARACTER_SET_CATALOG")

CHARACTER_SET_NAME = NON_RESERVED("CHARACTER_SET_NAME")

CHARACTER_SET_SCHEMA = NON_RESERVED("CHARACTER_SET_SCHEMA")

CHARACTERISTICS = NON_RESERVED("CHARACTERISTICS")

CHARACTERS = NON_RESERVED("CHARACTERS")

CLASS_ORIGIN = NON_RESERVED("CLASS_ORIGIN")

COBOL = NON_RESERVED("COBOL")

COLLATION = NON_RESERVED("COLLATION")

COLLATION_CATALOG = NON_RESERVED("COLLATION_CATALOG")

COLLATION_NAME = NON_RESERVED("COLLATION_NAME")

COLLATION_SCHEMA = NON_RESERVED("COLLATION_SCHEMA")

COLUMN_NAME = NON_RESERVED("COLUMN_NAME")

COMMAND_FUNCTION = NON_RESERVED("COMMAND_FUNCTION")

COMMAND_FUNCTION_CODE = NON_RESERVED("COMMAND_FUNCTION_CODE")

COMMITTED = NON_RESERVED("COMMITTED")

CONDITION_NUMBER = NON_RESERVED("CONDITION_NUMBER")

CONNECTION = NON_RESERVED("CONNECTION")

CONNECTION_NAME = NON_RESERVED("CONNECTION_NAME")

CONSTRAINT_CATALOG = NON_RESERVED("CONSTRAINT_CATALOG")

CONSTRAINT_NAME = NON_RESERVED("CONSTRAINT_NAME")

CONSTRAINT_SCHEMA = NON_RESERVED("CONSTRAINT_SCHEMA")

CONSTRAINTS = NON_RESERVED("CONSTRAINTS")

CONSTRUCTOR = NON_RESERVED("CONSTRUCTOR")

CONTAINS = NON_RESERVED("CONTAINS")

CONTINUE = NON_RESERVED("CONTINUE")

CURSOR_NAME = NON_RESERVED("CURSOR_NAME")

DATA = NON_RESERVED("DATA")

DATETIME_INTERVAL_CODE = NON_RESERVED("DATETIME_INTERVAL_CODE")

DATETIME_INTERVAL_PRECISION = NON_RESERVED("DATETIME_INTERVAL_PRECISION")

DEFAULTS = NON_RESERVED("DEFAULTS")

DEFERRABLE = NON_RESERVED("DEFERRABLE")

DEFERRED = NON_RESERVED("DEFERRED")

DEFINED = NON_RESERVED("DEFINED")

DEFINER = NON_RESERVED("DEFINER")

DEGREE = NON_RESERVED("DEGREE")

DEPTH = NON_RESERVED("DEPTH")

DERIVED = NON_RESERVED("DERIVED")

DESC = NON_RESERVED("DESC")

DESCRIPTOR = NON_RESERVED("DESCRIPTOR")

DIAGNOSTICS = NON_RESERVED("DIAGNOSTICS")

DISPATCH = NON_RESERVED("DISPATCH")

DOMAIN = NON_RESERVED("DOMAIN")

DYNAMIC_FUNCTION = NON_RESERVED("DYNAMIC_FUNCTION")

DYNAMIC_FUNCTION_CODE = NON_RESERVED("DYNAMIC_FUNCTION_CODE")

EQUALS = NON_RESERVED("EQUALS")

EXCEPTION = NON_RESERVED("EXCEPTION")

EXCLUDE = NON_RESERVED("EXCLUDE")

EXCLUDING = NON_RESERVED("EXCLUDING")

EXPLAIN = NON_RESERVED("EXPLAIN")

FINAL = NON_RESERVED("FINAL")

FIRST = NON_RESERVED("FIRST")

FOLLOWING = NON_RESERVED("FOLLOWING")

FORTRAN = NON_RESERVED("FORTRAN")

FOUND = NON_RESERVED("FOUND")

GENERAL = NON_RESERVED("GENERAL")

GENERATED = NON_RESERVED("GENERATED")

GO = NON_RESERVED("GO")

GOTO = NON_RESERVED("GOTO")

GRANTED = NON_RESERVED("GRANTED")

IMMEDIATE = NON_RESERVED("IMMEDIATE")

IMPLEMENTATION = NON_RESERVED("IMPLEMENTATION")

INCLUDING = NON_RESERVED("INCLUDING")

INCREMENT = NON_RESERVED("INCREMENT")

INDEX = NON_RESERVED("INDEX")

INITIALLY = NON_RESERVED("INITIALLY")

INPUT = NON_RESERVED("INPUT")

INSTANCE = NON_RESERVED("INSTANCE")

INSTANTIABLE = NON_RESERVED("INSTANTIABLE")

INVOKER = NON_RESERVED("INVOKER")

ISOLATION = NON_RESERVED("ISOLATION")

KEY = NON_RESERVED("KEY")

KEY_MEMBER = NON_RESERVED("KEY_MEMBER")

KEY_TYPE = NON_RESERVED("KEY_TYPE")

LAST = NON_RESERVED("LAST")

LENGTH = NON_RESERVED("LENGTH")

LEVEL = NON_RESERVED("LEVEL")

LOCATOR = NON_RESERVED("LOCATOR")

MAP = NON_RESERVED("MAP")

MATCHED = NON_RESERVED("MATCHED")

MAXVALUE = NON_RESERVED("MAXVALUE")

MESSAGE_LENGTH = NON_RESERVED("MESSAGE_LENGTH")

MESSAGE_OCTET_LENGTH = NON_RESERVED("MESSAGE_OCTET_LENGTH")

MESSAGE_TEXT = NON_RESERVED("MESSAGE_TEXT")

MINVALUE = NON_RESERVED("MINVALUE")

MORE = NON_RESERVED("MORE")

MUMPS = NON_RESERVED("MUMPS")

NAME = NON_RESERVED("NAME")

NAMES = NON_RESERVED("NAMES")

NESTING = NON_RESERVED("NESTING")

NEXT = NON_RESERVED("NEXT")

NORMALIZED = NON_RESERVED("NORMALIZED")

NULLABLE = NON_RESERVED("NULLABLE")

NULLS = NON_RESERVED("NULLS")

NUMBER = NON_RESERVED("NUMBER")

OBJECT = NON_RESERVED("OBJECT")

OCTETS = NON_RESERVED("OCTETS")

OPTION = NON_RESERVED("OPTION")

OPTIONS = NON_RESERVED("OPTIONS")

ORDERING = NON_RESERVED("ORDERING")

ORDINALITY = NON_RESERVED("ORDINALITY")

OTHERS = NON_RESERVED("OTHERS")

OUTPUT = NON_RESERVED("OUTPUT")

OVERRIDING = NON_RESERVED("OVERRIDING")

PAD = NON_RESERVED("PAD")

PARAMETER_MODE = NON_RESERVED("PARAMETER_MODE")

PARAMETER_NAME = NON_RESERVED("PARAMETER_NAME")

PARAMETER_ORDINAL_POSITION = NON_RESERVED("PARAMETER_ORDINAL_POSITION")

PARAMETER_SPECIFIC_CATALOG = NON_RESERVED("PARAMETER_SPECIFIC_CATALOG")

PARAMETER_SPECIFIC_NAME = NON_RESERVED("PARAMETER_SPECIFIC_NAME")

PARAMETER_SPECIFIC_SCHEMA = NON_RESERVED("PARAMETER_SPECIFIC_SCHEMA")

PARTIAL = NON_RESERVED("PARTIAL")

PASCAL = NON_RESERVED("PASCAL")

PATH = NON_RESERVED("PATH")

PLACING = NON_RESERVED("PLACING")

PLI = NON_RESERVED("PLI")

PRECEDING = NON_RESERVED("PRECEDING")

PRESERVE = NON_RESERVED("PRESERVE")

PRIOR = NON_RESERVED("PRIOR")

PRIVILEGES = NON_RESERVED("PRIVILEGES")

PUBLIC = NON_RESERVED("PUBLIC")

READ = NON_RESERVED("READ")

RELATIVE = NON_RESERVED("RELATIVE")

REPEATABLE = NON_RESERVED("REPEATABLE")

RESTART = NON_RESERVED("RESTART")

RESTRICT = NON_RESERVED("RESTRICT")

RETURNED_CARDINALITY = NON_RESERVED("RETURNED_CARDINALITY")

RETURNED_LENGTH = NON_RESERVED("RETURNED_LENGTH")

RETURNED_OCTET_LENGTH = NON_RESERVED("RETURNED_OCTET_LENGTH")

RETURNED_SQLSTATE = NON_RESERVED("RETURNED_SQLSTATE")

ROLE = NON_RESERVED("ROLE")

ROUTINE = NON_RESERVED("ROUTINE")

ROUTINE_CATALOG = NON_RESERVED("ROUTINE_CATALOG")

ROUTINE_NAME = NON_RESERVED("ROUTINE_NAME")

ROUTINE_SCHEMA = NON_RESERVED("ROUTINE_SCHEMA")

ROW_COUNT = NON_RESERVED("ROW_COUNT")

SCALE = NON_RESERVED("SCALE")

SCHEMA = NON_RESERVED("SCHEMA")

SCHEMA_NAME = NON_RESERVED("SCHEMA_NAME")

SCOPE_CATALOG = NON_RESERVED("SCOPE_CATALOG")

SCOPE_NAME = NON_RESERVED("SCOPE_NAME")

SCOPE_SCHEMA = NON_RESERVED("SCOPE_SCHEMA")

SECTION = NON_RESERVED("SECTION")

SECURITY = NON_RESERVED("SECURITY")

SELF = NON_RESERVED("SELF")

SEQUENCE = NON_RESERVED("SEQUENCE")

SERIALIZABLE = NON_RESERVED("SERIALIZABLE")

SERVER_NAME = NON_RESERVED("SERVER_NAME")

SESSION = NON_RESERVED("SESSION")

SETS = NON_RESERVED("SETS")

SIMPLE = NON_RESERVED("SIMPLE")

SIZE = NON_RESERVED("SIZE")

SOURCE = NON_RESERVED("SOURCE")

SPACE = NON_RESERVED("SPACE")

SPECIFIC_NAME = NON_RESERVED("SPECIFIC_NAME")

STATE = NON_RESERVED("STATE")

STATEMENT = NON_RESERVED("STATEMENT")

STRUCTURE = NON_RESERVED("STRUCTURE")

STYLE = NON_RESERVED("STYLE")

SUBCLASS_ORIGIN = NON_RESERVED("SUBCLASS_ORIGIN")

TABLE_NAME = NON_RESERVED("TABLE_NAME")

TEMPORARY = NON_RESERVED("TEMPORARY")

TIES = NON_RESERVED("TIES")

TOP_LEVEL_COUNT = NON_RESERVED("TOP_LEVEL_COUNT")

TRANSACTION = NON_RESERVED("TRANSACTION")

TRANSACTION_ACTIVE = NON_RESERVED("TRANSACTION_ACTIVE")

TRANSACTIONS_COMMITTED = NON_RESERVED("TRANSACTIONS_COMMITTED")

TRANSACTIONS_ROLLED_BACK = NON_RESERVED("TRANSACTIONS_ROLLED_BACK")

TRANSFORM = NON_RESERVED("TRANSFORM")

TRANSFORMS = NON_RESERVED("TRANSFORMS")

TRIGGER_CATALOG = NON_RESERVED("TRIGGER_CATALOG")

TRIGGER_NAME = NON_RESERVED("TRIGGER_NAME")

TRIGGER_SCHEMA = NON_RESERVED("TRIGGER_SCHEMA")

TYPE = NON_RESERVED("TYPE")

UNBOUNDED = NON_RESERVED("UNBOUNDED")

UNCOMMITTED = NON_RESERVED("UNCOMMITTED")

UNDER = NON_RESERVED("UNDER")

UNNAMED = NON_RESERVED("UNNAMED")

USAGE = NON_RESERVED("USAGE")

USER_DEFINED_TYPE_CATALOG = NON_RESERVED("USER_DEFINED_TYPE_CATALOG")

USER_DEFINED_TYPE_CODE = NON_RESERVED("USER_DEFINED_TYPE_CODE")

USER_DEFINED_TYPE_NAME = NON_RESERVED("USER_DEFINED_TYPE_NAME")

USER_DEFINED_TYPE_SCHEMA = NON_RESERVED("USER_DEFINED_TYPE_SCHEMA")

VIEW = NON_RESERVED("VIEW")

WORK = NON_RESERVED("WORK")

WRITE = NON_RESERVED("WRITE")

ZONE = NON_RESERVED("ZONE")
