from . import KEYWORD


class RESERVED(KEYWORD):
    ...


ABS = RESERVED("ABS")

ALL = RESERVED("ALL")

ALLOCATE = RESERVED("ALLOCATE")

ALTER = RESERVED("ALTER")

AND = RESERVED("AND")

ANY = RESERVED("ANY")

ARE = RESERVED("ARE")

ARRAY = RESERVED("ARRAY")

AS = RESERVED("AS")

ASENSITIVE = RESERVED("ASENSITIVE")

ASYMMETRIC = RESERVED("ASYMMETRIC")

AT = RESERVED("AT")

ATOMIC = RESERVED("ATOMIC")

AUTHORIZATION = RESERVED("AUTHORIZATION")

AVG = RESERVED("AVG")

BEGIN = RESERVED("BEGIN")

BETWEEN = RESERVED("BETWEEN")

BIGINT = RESERVED("BIGINT")

BINARY = RESERVED("BINARY")

BLOB = RESERVED("BLOB")

BOOLEAN = RESERVED("BOOLEAN")

BOTH = RESERVED("BOTH")

BY = RESERVED("BY")

CALL = RESERVED("CALL")

CALLED = RESERVED("CALLED")

CARDINALITY = RESERVED("CARDINALITY")

CASCADED = RESERVED("CASCADED")

CASE = RESERVED("CASE")

CAST = RESERVED("CAST")

CEIL = RESERVED("CEIL")

CEILING = RESERVED("CEILING")

CHAR = RESERVED("CHAR")

CHAR_LENGTH = RESERVED("CHAR_LENGTH")

CHARACTER = RESERVED("CHARACTER")

CHARACTER_LENGTH = RESERVED("CHARACTER_LENGTH")

CHECK = RESERVED("CHECK")

CLOB = RESERVED("CLOB")

CLOSE = RESERVED("CLOSE")

COALESCE = RESERVED("COALESCE")

COLLATE = RESERVED("COLLATE")

COLLECT = RESERVED("COLLECT")

COLUMN = RESERVED("COLUMN")

COMMIT = RESERVED("COMMIT")

CONDITION = RESERVED("CONDITION")

CONNECT = RESERVED("CONNECT")

CONSTRAINT = RESERVED("CONSTRAINT")

CONVERT = RESERVED("CONVERT")

CORR = RESERVED("CORR")

CORRESPONDING = RESERVED("CORRESPONDING")

COUNT = RESERVED("COUNT")

COVAR_POP = RESERVED("COVAR_POP")

COVAR_SAMP = RESERVED("COVAR_SAMP")

CREATE = RESERVED("CREATE")

CROSS = RESERVED("CROSS")

CUBE = RESERVED("CUBE")

CUME_DIST = RESERVED("CUME_DIST")

CURRENT = RESERVED("CURRENT")

CURRENT_DATE = RESERVED("CURRENT_DATE")

CURRENT_DEFAULT_ = RESERVED("CURRENT_DEFAULT_")

TRANSFORM_GROUP = RESERVED("TRANSFORM_GROUP")

CURRENT_PATH = RESERVED("CURRENT_PATH")

CURRENT_ROLE = RESERVED("CURRENT_ROLE")

CURRENT_TIME = RESERVED("CURRENT_TIME")

CURRENT_TIMESTAMP = RESERVED("CURRENT_TIMESTAMP")

CURRENT_TRANSFORM_ = RESERVED("CURRENT_TRANSFORM_")

GROUP_FOR_TYPE = RESERVED("GROUP_FOR_TYPE")

CURRENT_USER = RESERVED("CURRENT_USER")

CURSOR = RESERVED("CURSOR")

CYCLE = RESERVED("CYCLE")

DATE = RESERVED("DATE")

DAY = RESERVED("DAY")

DEALLOCATE = RESERVED("DEALLOCATE")

DEC = RESERVED("DEC")

DECIMAL = RESERVED("DECIMAL")

DECLARE = RESERVED("DECLARE")

DEFAULT = RESERVED("DEFAULT")

DELETE = RESERVED("DELETE")

DENSE_RANK = RESERVED("DENSE_RANK")

DEREF = RESERVED("DEREF")

DESCRIBE = RESERVED("DESCRIBE")

DETERMINISTIC = RESERVED("DETERMINISTIC")

DISCONNECT = RESERVED("DISCONNECT")

DISTINCT = RESERVED("DISTINCT")

DOUBLE = RESERVED("DOUBLE")

DROP = RESERVED("DROP")

DYNAMIC = RESERVED("DYNAMIC")

EACH = RESERVED("EACH")

ELEMENT = RESERVED("ELEMENT")

ELSE = RESERVED("ELSE")

END = RESERVED("END")

END_EXEC = RESERVED("END-EXEC")

ESCAPE = RESERVED("ESCAPE")

EVERY = RESERVED("EVERY")

EXCEPT = RESERVED("EXCEPT")

EXEC = RESERVED("EXEC")

EXECUTE = RESERVED("EXECUTE")

EXISTS = RESERVED("EXISTS")

EXP = RESERVED("EXP")

EXTERNAL = RESERVED("EXTERNAL")

EXTRACT = RESERVED("EXTRACT")

FALSE = RESERVED("FALSE")

FETCH = RESERVED("FETCH")

FILTER = RESERVED("FILTER")

FLOAT = RESERVED("FLOAT")

FLOOR = RESERVED("FLOOR")

FOR = RESERVED("FOR")

FOREIGN = RESERVED("FOREIGN")

FREE = RESERVED("FREE")

FROM = RESERVED("FROM")

FULL = RESERVED("FULL")

FUNCTION = RESERVED("FUNCTION")

FUSION = RESERVED("FUSION")

GET = RESERVED("GET")

GLOBAL = RESERVED("GLOBAL")

GRANT = RESERVED("GRANT")

GROUP = RESERVED("GROUP")

GROUPING = RESERVED("GROUPING")

HAVING = RESERVED("HAVING")

HOLD = RESERVED("HOLD")

HOUR = RESERVED("HOUR")

IDENTITY = RESERVED("IDENTITY")

IN = RESERVED("IN")

INDICATOR = RESERVED("INDICATOR")

INNER = RESERVED("INNER")

INOUT = RESERVED("INOUT")

INSENSITIVE = RESERVED("INSENSITIVE")

INSERT = RESERVED("INSERT")

INT = RESERVED("INT")

INTEGER = RESERVED("INTEGER")

INTERSECT = RESERVED("INTERSECT")

INTERSECTION = RESERVED("INTERSECTION")

INTERVAL = RESERVED("INTERVAL")

INTO = RESERVED("INTO")

IS = RESERVED("IS")

JOIN = RESERVED("JOIN")

LANGUAGE = RESERVED("LANGUAGE")

LARGE = RESERVED("LARGE")

LATERAL = RESERVED("LATERAL")

LEADING = RESERVED("LEADING")

LEFT = RESERVED("LEFT")

LIKE = RESERVED("LIKE")

LN = RESERVED("LN")

LOCAL = RESERVED("LOCAL")

LOCALTIME = RESERVED("LOCALTIME")

LOCALTIMESTAMP = RESERVED("LOCALTIMESTAMP")

LOWER = RESERVED("LOWER")

MATCH = RESERVED("MATCH")

MAX = RESERVED("MAX")

MEMBER = RESERVED("MEMBER")

MERGE = RESERVED("MERGE")

METHOD = RESERVED("METHOD")

MIN = RESERVED("MIN")

MINUTE = RESERVED("MINUTE")

MOD = RESERVED("MOD")

MODIFIES = RESERVED("MODIFIES")

MODULE = RESERVED("MODULE")

MONTH = RESERVED("MONTH")

MULTISET = RESERVED("MULTISET")

NATIONAL = RESERVED("NATIONAL")

NATURAL = RESERVED("NATURAL")

NCHAR = RESERVED("NCHAR")

NCLOB = RESERVED("NCLOB")

NEW = RESERVED("NEW")

NO = RESERVED("NO")

NONE = RESERVED("NONE")

NORMALIZE = RESERVED("NORMALIZE")

NOT = RESERVED("NOT")

NULL = RESERVED("NULL")

NULLIF = RESERVED("NULLIF")

NUMERIC = RESERVED("NUMERIC")

OCTET_LENGTH = RESERVED("OCTET_LENGTH")

OF = RESERVED("OF")

OLD = RESERVED("OLD")

ON = RESERVED("ON")

ONLY = RESERVED("ONLY")

OPEN = RESERVED("OPEN")

OR = RESERVED("OR")

ORDER = RESERVED("ORDER")

OUT = RESERVED("OUT")

OUTER = RESERVED("OUTER")

OVER = RESERVED("OVER")

OVERLAPS = RESERVED("OVERLAPS")

OVERLAY = RESERVED("OVERLAY")

PARAMETER = RESERVED("PARAMETER")

PARTITION = RESERVED("PARTITION")

PERCENT_RANK = RESERVED("PERCENT_RANK")

PERCENTILE_CONT = RESERVED("PERCENTILE_CONT")

PERCENTILE_DISC = RESERVED("PERCENTILE_DISC")

POSITION = RESERVED("POSITION")

POWER = RESERVED("POWER")

PRECISION = RESERVED("PRECISION")

PREPARE = RESERVED("PREPARE")

PRIMARY = RESERVED("PRIMARY")

PROCEDURE = RESERVED("PROCEDURE")

RANGE = RESERVED("RANGE")

RANK = RESERVED("RANK")

READS = RESERVED("READS")

REAL = RESERVED("REAL")

RECURSIVE = RESERVED("RECURSIVE")

REF = RESERVED("REF")

REFERENCES = RESERVED("REFERENCES")

REFERENCING = RESERVED("REFERENCING")

REGR_AVGX = RESERVED("REGR_AVGX")

REGR_AVGY = RESERVED("REGR_AVGY")

REGR_COUNT = RESERVED("REGR_COUNT")

REGR_INTERCEPT = RESERVED("REGR_INTERCEPT")

REGR_R2 = RESERVED("REGR_R2")

REGR_SLOPE = RESERVED("REGR_SLOPE")

REGR_SXX = RESERVED("REGR_SXX")

REGR_SXY = RESERVED("REGR_SXY")

REGR_SYY = RESERVED("REGR_SYY")

RELEASE = RESERVED("RELEASE")

RESULT = RESERVED("RESULT")

RETURN = RESERVED("RETURN")

RETURNS = RESERVED("RETURNS")

REVOKE = RESERVED("REVOKE")

RIGHT = RESERVED("RIGHT")

ROLLBACK = RESERVED("ROLLBACK")

ROLLUP = RESERVED("ROLLUP")

ROW = RESERVED("ROW")

ROW_NUMBER = RESERVED("ROW_NUMBER")

ROWS = RESERVED("ROWS")

SAVEPOINT = RESERVED("SAVEPOINT")

SCOPE = RESERVED("SCOPE")

SCROLL = RESERVED("SCROLL")

SEARCH = RESERVED("SEARCH")

SECOND = RESERVED("SECOND")

SELECT = RESERVED("SELECT")

SENSITIVE = RESERVED("SENSITIVE")

SESSION_USER = RESERVED("SESSION_USER")

SET = RESERVED("SET")

SIMILAR = RESERVED("SIMILAR")

SMALLINT = RESERVED("SMALLINT")

SOME = RESERVED("SOME")

SPECIFIC = RESERVED("SPECIFIC")

SPECIFICTYPE = RESERVED("SPECIFICTYPE")

SQL = RESERVED("SQL")

SQLEXCEPTION = RESERVED("SQLEXCEPTION")

SQLSTATE = RESERVED("SQLSTATE")

SQLWARNING = RESERVED("SQLWARNING")

SQRT = RESERVED("SQRT")

START = RESERVED("START")

STATIC = RESERVED("STATIC")

STDDEV_POP = RESERVED("STDDEV_POP")

STDDEV_SAMP = RESERVED("STDDEV_SAMP")

SUBMULTISET = RESERVED("SUBMULTISET")

SUBSTRING = RESERVED("SUBSTRING")

SUM = RESERVED("SUM")

SYMMETRIC = RESERVED("SYMMETRIC")

SYSTEM = RESERVED("SYSTEM")

SYSTEM_USER = RESERVED("SYSTEM_USER")

TABLE = RESERVED("TABLE")

TABLESAMPLE = RESERVED("TABLESAMPLE")

THEN = RESERVED("THEN")

TIME = RESERVED("TIME")

TIMESTAMP = RESERVED("TIMESTAMP")

TIMEZONE_HOUR = RESERVED("TIMEZONE_HOUR")

TIMEZONE_MINUTE = RESERVED("TIMEZONE_MINUTE")

TO = RESERVED("TO")

TRAILING = RESERVED("TRAILING")

TRANSLATE = RESERVED("TRANSLATE")

TRANSLATION = RESERVED("TRANSLATION")

TREAT = RESERVED("TREAT")

TRIGGER = RESERVED("TRIGGER")

TRIM = RESERVED("TRIM")

TRUE = RESERVED("TRUE")

UESCAPE = RESERVED("UESCAPE")

UNION = RESERVED("UNION")

UNIQUE = RESERVED("UNIQUE")

UNKNOWN = RESERVED("UNKNOWN")

UNNEST = RESERVED("UNNEST")

UPDATE = RESERVED("UPDATE")

UPPER = RESERVED("UPPER")

USER = RESERVED("USER")

USING = RESERVED("USING")

VALUE = RESERVED("VALUE")

VALUES = RESERVED("VALUES")

VAR_POP = RESERVED("VAR_POP")

VAR_SAMP = RESERVED("VAR_SAMP")

VARCHAR = RESERVED("VARCHAR")

VARYING = RESERVED("VARYING")

WHEN = RESERVED("WHEN")

WHENEVER = RESERVED("WHENEVER")

WHERE = RESERVED("WHERE")

WIDTH_BUCKET = RESERVED("WIDTH_BUCKET")

WINDOW = RESERVED("WINDOW")

WITH = RESERVED("WITH")

WITHIN = RESERVED("WITHIN")

WITHOUT = RESERVED("WITHOUT")

YEAR = RESERVED("YEAR")
